### ISSUE TITLE
Tables with foreign keys

### ISSUE THREAD

**Issue by jtescher** [adangel/liquibase-percona#1]
When `pt-online-schema-change` is executed on a table with foreign keys it requires that you set an alter foreign keys method. Currently `liquibase-percona` does not set this option as far as I can see.

Resulting error is:
`You did not specify --alter-foreign-keys-method, but there are foreign keys that reference the table. Please read the tool's documentation carefully.`

Which results in: `Error: Percona exited with 1` from `liquibase migrate`

Versions:
liquibase-percona: 1.1.0
Liquibase: 3.3.5
pt-online-schema-change: 2.2.14

**Comment by adangel** [comment]
The new version liquibase-percona 1.1.1 now adds `--alter-foreign-keys-method=auto` to the command line for pt-online-schema-change.
