### ISSUE TITLE
Rollback of foreign key constraint changing constraint names problem

### ISSUE THREAD

**Issue by paulozenida** [adangel/liquibase-percona#14]
Hello.

I'm trying to include liquibase-percona in one of my projects and I've been facing an issue related to the rollback of foreign keys. I have the following changeSets:

```
<changeSet author="paulozenida" id="ID1">
  <addForeignKeyConstraint baseColumnNames="source_id" baseTableName="service_auth_credentials" constraintName="FK_1" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="id" eferencedTableName="service"/>
</changeSet>

<changeSet author="paulozenida" id="ID2">
  <addForeignKeyConstraint baseColumnNames="auth_config_id" baseTableName="service" constraintName="FK_2" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="id" referencedTableName="service_auth_config"/>
</changeSet>
```

If I rollback ID2, the foreign keys of table service_auth_credentials are renamed to include '_' at the beginning. Therefore, when I try to rollback ID1, I get an error because the FK_1 does not exist. 

Basically, if I execute `./liquibase --outputFile=migrate.sql rollbackCountSQL 2`

The rollback operations would be similar to:

```
pt-online-schema-change --alter="DROP FOREIGN KEY _FK_2" --alter-foreign-keys-method=auto --host=127.0.0.1 --port=3306 --user=root --execute D=serviceauth,t=service;
pt-online-schema-change --alter="DROP FOREIGN KEY _FK_1" --alter-foreign-keys-method=auto --host=127.0.0.1 --port=3306 --user=root --execute D=serviceauth,t=service_auth_credentials;
```

The problem is that the first rollback will change the original FK_1 to _FK1 so, when the second rollback operation is performed, there is no FK1 foreign key to be dropped.

Any ideas on how to make this work properly?

**Comment by adangel** [comment]
@paulozenida Thanks for the report!

The option `--alter-foreign-keys-method=auto` has been added with #1.
Would it help, to have this property configurable? We'd also need to adjust the behaviour of [PerconaDropForeignKeyConstraintChange](https://github.com/adangel/liquibase-percona/blob/master/src/main/java/liquibase/ext/percona/PerconaDropForeignKeyConstraintChange.java#L43), since we need or do not need to add the underscore.

I fear, that this wouldn't solve the problem, and you could run into the same problem, if the tables are big (then pt-osc would automatically switch to "drop_swap"...)

I think, what we need to do is, determine the name of the foreign key constraint at runtime, so that we know, if we need to prefix with an underscore or not...

**Comment by paulozenida** [comment]
@adangel Thank your for your answer. Making the option "alter-foreign-keys-method" configurable could help, I suppose, because one could set it to drop_swap by default and, in that case, I supposed the foreign keys would not be renamed. At the time being, I simply disabled the dropForeignKeyConstraint by setting the system property liquibase.percona.skipChanges to dropForeignKeyConstraint, which means I'm simply not using percona for those situations. 

However, your suggestion to check the name of the foreign key constraint at runtime would be a much clever and interesting solution ;-)

**Comment by adangel** [comment]
@paulozenida 
I think, I've fixed this issue.
Would you mind to test it?
Just use the snapshot version as described here: https://github.com/adangel/liquibase-percona#using-snapshots
Thanks!

**Comment by paulozenida** [comment]
Hello @adangel .

I tried to test it with the following setup but it didn't work:

1 - Create the tables:
`
create table service_auth_credentials (id int(11), source_id int(11), primary key(id));
create table service (id int(11), auth_config_id int(11), primary key(id));
create table service_auth_config (id int(11), primary key(id));
`

2 - Include the changesets:
`
<changeSet author="paulozenida" id="ID1">
  <addForeignKeyConstraint baseColumnNames="source_id" baseTableName="service_auth_credentials" constraintName="FK_1" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="id" referencedTableName="service"/>
</changeSet>
<changeSet author="paulozenida" id="ID2">
  <addForeignKeyConstraint baseColumnNames="auth_config_id" baseTableName="service" constraintName="FK_2" deferrable="false" initiallyDeferred="false" onDelete="NO ACTION" onUpdate="NO ACTION" referencedColumnNames="id" referencedTableName="service_auth_config"/>
</changeSet>
`

3 - Updating liquibase-percona lib in lib folder:
`liquibase-percona-1.5.0-20180928.111013-1.jar`

4 - Configuring liquibase file: 
`
#!/usr/bin/env bash

if [ ! -n "${LIQUIBASE_HOME+x}" ]; then
  # echo "LIQUIBASE_HOME is not set."

  ## resolve links - $0 may be a symlink
  PRG="$0"
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done


  LIQUIBASE_HOME=`dirname "$PRG"`

  # make it fully qualified
  LIQUIBASE_HOME=`cd "$LIQUIBASE_HOME" && pwd`
  # echo "Liquibase Home: $LIQUIBASE_HOME"
fi


# build classpath from all jars in lib
if [ -f /usr/bin/cygpath ]; then
  CP=.
  for i in "$LIQUIBASE_HOME"/liquibase*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
  for i in "$LIQUIBASE_HOME"/lib/*.jar; do
    i=`cygpath --windows "$i"`
    CP="$CP;$i"
  done
else
  if [[ $(uname) = MINGW* ]]; then
    CP_SEPARATOR=";"
  else
    CP_SEPARATOR=":"
  fi
  CP=.
  for i in "$LIQUIBASE_HOME"/liquibase*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
  for i in "$LIQUIBASE_HOME"/lib/*.jar; do
    CP="$CP""$CP_SEPARATOR""$i"
  done
fi

java -cp "$CP" $JAVA_OPTS liquibase.integration.commandline.Main ${1+"$@"}
`

But the output doesn't look good because, with this version, I can't even create the foreign keys. Here's the output of the command `./liquibase update`:

`
...
DEBUG 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Computed checksum for addForeignKeyConstraint:[
    baseColumnNames="source_id"
    baseTableName="service_auth_credentials"
    constraintName="FK_1"
    deferrable="false"
    initiallyDeferred="false"
    onDelete="NO ACTION"
    onUpdate="NO ACTION"
    referencedColumnNames="id"
    referencedTableName="service"
] as a17bbae4f12a7b48c1220f1fd242e636
DEBUG 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Computed checksum for 7:a17bbae4f12a7b48c1220f1fd242e636: as befa9afe60648f4aa014b932fac07ed1
DEBUG 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Running Changeset:changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida
DEBUG 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Changeset changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida
DEBUG 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Reading ChangeSet: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida
DEBUG 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Executing Statement: PTOnlineSchemaChangeStatement[database: null, table: service_auth_credentials, alterStatement: ADD CONSTRAINT FK_1 FOREIGN KEY (source_id) REFERENCES hooksubscriber.service (id) ON DELETE NO ACTION ON UPDATE NO ACTION]
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Executing: pt-online-schema-change --alter="ADD CONSTRAINT FK_1 FOREIGN KEY (source_id) REFERENCES hooksubscriber.service (id) ON DELETE NO ACTION ON UPDATE NO ACTION" --alter-foreign-keys-method=auto --nocheck-unique-key-change --host=127.0.0.1 --port=3306 --user=root --password=*** --execute D=hooksubscriber,t=service_auth_credentials
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Option password requires an argument
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Usage: pt-online-schema-change [OPTIONS] DSN
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Errors in command-line arguments:
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida:   * Error parsing options
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: pt-online-schema-change alters a table's structure without blocking reads or
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: writes.  Specify the database and table in the DSN.  Do not use this tool before
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: reading its documentation and checking your backups carefully.  For more
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: details, please use the --help option, or try 'perldoc
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: /usr/local/Cellar/percona-toolkit/3.0.10_1/libexec/bin/pt-online-schema-change'
INFO 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: for complete documentation.
SEVERE 9/28/18 3:11 PM: liquibase: db.changelog-master.xml: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Change Set changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida failed.  Error: Percona exited with 1
DEBUG 9/28/18 3:11 PM: liquibase: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Release Database Lock
DEBUG 9/28/18 3:11 PM: liquibase: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Executing UPDATE database command: UPDATE hooksubscriber.DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1
INFO 9/28/18 3:11 PM: liquibase: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Successfully released change log lock
Unexpected error running Liquibase: Percona exited with 1

SEVERE 9/28/18 3:11 PM: liquibase: changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida: Percona exited with 1
liquibase.exception.MigrationFailedException: Migration failed for change set changesets/1.4.6/changeset-2018-07-24.xml::ID1::paulozenida:
     Reason: java.lang.RuntimeException: Percona exited with 1
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
	at liquibase.Liquibase.update(Liquibase.java:214)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1130)
	at liquibase.integration.commandline.Main.run(Main.java:188)
	at liquibase.integration.commandline.Main.main(Main.java:103)
Caused by: java.lang.RuntimeException: Percona exited with 1
	at liquibase.ext.percona.PTOnlineSchemaChangeStatement.generate(PTOnlineSchemaChangeStatement.java:221)
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:19)
	at liquibase.sqlgenerator.core.RuntimeGenerator.generateSql(RuntimeGenerator.java:10)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:225)
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
	at liquibase.executor.jvm.JdbcExecutor.access$500(JdbcExecutor.java:36)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:295)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
	... 7 more
`

Any ideas of what may be causing this issue?

**Comment by adangel** [comment]
Thanks for testing!

It is trying to execute the following pt-osc command:

`Executing: pt-online-schema-change --alter="ADD CONSTRAINT FK_1 FOREIGN KEY (source_id) REFERENCES hooksubscriber.service (id) ON DELETE NO ACTION ON UPDATE NO ACTION" --alter-foreign-keys-method=auto --nocheck-unique-key-change --host=127.0.0.1 --port=3306 --user=root --password=*** --execute D=hooksubscriber,t=service_auth_credentials`

I see then this log output:

`Option password requires an argument`
Note: The real password is replaced by liquibase-percona with "***" in order to not leak the password into the log files. So, the command looks ok. But the log entry "Option password requires an argument" together with "Error parsing options" doesn't look ok....

Do we have a problem now determining the password for mysql?

The other thing I'd try out: You seem to use pt-osc version 3.0.10, I've only tested version 3.0.12. Maybe something has been changed there?
Also, which version of liquibase are you using?

**Comment by paulozenida** [comment]
Yes, that was exactly the problem. I forgot I had to comment the password from liquibase.properties in order to make it work. Everything seemed ok.

And to answer your question, I'm using liquibase 3.5.2

**Comment by paulozenida** [comment]
Well, I guess you can release a new version, yes, because it seems to resolve this particular issue and no new bugs have showed up ;)

**Comment by adangel** [comment]
1.5.0 is just now released. Thanks for testing!
