### ISSUE TITLE
Failing test PerconaAddForeignKeyConstraintChangeTest

### ISSUE THREAD

**Issue by paulozenida** [adangel/liquibase-percona#16]
When I build the project locally, there are failing tests:
[INFO]
[ERROR] Failures:
[ERROR]   PerconaAddForeignKeyConstraintChangeTest.testSelfReferencingForeignKey:174 expected:<[0.0.0]> but was:<[3.0.5]>
[INFO]
[ERROR] Tests run: 99, Failures: 1, Errors: 0, Skipped: 2
[INFO]

**Comment by paulozenida** [comment]
I believe the one from the version may be fixed with the following change (if there is a version of percona-toolkit in the path - another tests seems to be have loaded it - the output seems to be different):

    @Test
    public void testSelfReferencingForeignKey() {
        ...

        PerconaToolkitVersion version = PTOnlineSchemaChangeStatement.getVersion();
        assertTrue(PTOnlineSchemaChangeStatement.available);

        if("0.0.0".equals(version.toString())) {
            setTargetTableName("person");
            assertPerconaChange(
                "ADD CONSTRAINT fk_person_parent FOREIGN KEY (parent) REFERENCES _person_new (id)",
                change.generateStatements(getDatabase()));
        }
    }

**Comment by adangel** [comment]
Thanks, I could reproduce it: If the test `liquibase.ext.percona.PTOnlineSchemaChangeStatementTest` is executed before, then it fails.

Background info: the version of the tool is detected once and then cached. In the unit tests, we usually bypass this detection, except for this special test in PTOnlineSchemaChangeStatementTest... this test doesn't restore the original state in the end...
