### ISSUE TITLE
Cross database bug

### ISSUE THREAD

**Issue by koleo** [adangel/liquibase-percona#22]
Command generated by liquibase-percona plugin v1.4.0 for cross-schema changes is buggy.

Suppose the following changeset:

```
    <changeSet id="123" author="me">
        <addColumn catalogName="db2" tableName="tbl">
            <column name="mycol" type="integer" />
        </addColumn>
    </changeSet>
```

Running _liquibase updateSQL_ from **another db** (db1)...

> liquibase --driver=com.mysql.jdbc.Driver --classpath="/usr/share/java/mysql-connector-java.jar" --url="jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=UTF-8" --username="myuser" --password="xxxxxx"  updatesql

... produces the following script:

```
--  Changeset mychangeset.xml::123::me
--  pt-online-schema-change --alter="ADD COLUMN mycol INT NULL" --alter-foreign-keys-method=auto --host=127.0.0.1 --port=3306 --user=myuser --password=*** --execute D=db1,t=tbl;

--  Instead of the following statements, pt-online-schema-change will be used;

ALTER TABLE db2.tbl ADD mycol INT NULL;
```

As you can see the SQL command (from liquibase core) add the column `db2.tbl`, as expected.
But pt-online-schema-change add the column to the default database : `db1.tbl`!

**Comment by adangel** [comment]
@koleo 
I think, I've fixed this issue.
Would you mind to test it?
Just use the snapshot version as described here: https://github.com/adangel/liquibase-percona#using-snapshots
Thanks!
