### ISSUE TITLE
Strange behavior when liquibase.percona.defaultOn is false

### ISSUE THREAD

**Issue by bellatoris** [adangel/liquibase-percona#28]
First of all, thank you very much of your awesome works.

>  Settings this property to false allows to control for each single change, whether to use Percona Toolkit or not.

However, if `defaultOn` is false, below snippet always return true. Therefore every changeset will not use percona toolkit.

https://github.com/adangel/liquibase-percona/blob/c8f1089feb0a06430df938b3fc5c02c67ab91fc2/src/main/java/liquibase/ext/percona/PerconaChangeUtil.java#L68

**Comment by adangel** [comment]
Thanks for reporting.

Let me try to summarize the problem: You are having a couple of changes. By default, you do not want to use percona toolkit, but only for selected ones. Therefore, you set "defaultOn=false" and for the specific changes, you set "usePercona: true".

You are right, with that combination, the change still won't use percona. Definitively a bug.
