### ISSUE TITLE
liquibase-percona - changeset formatted xml vs. sql

### ISSUE THREAD

**Issue by sce-release-watch** [adangel/liquibase-percona#51]
Hi,

this is rather a question I think I already know the answer to. Might be worth to put a line or two about this in the readme though.

Anyway, we're using liquibase in a fairly simple way at the moment with changesets not through XML, but formatted as sql.

What about liquibase-percona? Does it require changesets as XML?

Thanks,
Holger

**Comment by adangel** [comment]
Are you using [Formatted SQL](http://www.liquibase.org/documentation/sql_format.html) changelog? I think, this won't work, as all changes there are converted into custom sql refactoring. Liquibase percona needs to know the actual refactorings (add column, etc.).
Liquibase percona should work with changelogs in the formats XML, YAML and JSON.

**Comment by sce-release-watch** [comment]
Yes, formatted SQL - thanks for taking the time to look at this; seems that we have to move to XML/YAML/JSON :)
