### ISSUE TITLE
Percona losing connection while performing DB upgrade 

### ISSUE THREAD

**Issue by chiragag18** [adangel/liquibase-percona#52]
I am adding two column to client table. I am using liquibase to manage DB versioning below is the final command is creating for that change. 

pt-online-schema-change --alter-foreign-keys-method=auto --max-load=Threads_running:300 --critical-load=Threads_running:400 --alter="ADD COLUMN text1 VARCHAR(255) NULL, ADD COLUMN text2 VARCHAR(255) NULL" --host=test.us-east-1.rds.amazonaws.com --port=3306 --user=**** --password=*** --execute D=ledgertxns,t=client

liquibase-percona:1.6.0
liquibase-core:3.6.3
mysql-connector-java:5.1.38
percona-toolkit-3.0.13

This DB instance is having many client connect at a time, so I have maximize the value of max-load and critical-load and I can see these values are setting properly from log

Thread-2] liquibase.Liquibase                      :   --max-load Threads_running:300
 Thread-2] liquibase.Liquibase                      :   --critial-load Threads_running:400

But above these two lines i am also getting an information which is - 

Error checking --max-load or --critial-load: DBD::mysql::st execute failed: Lost connection to MySQL server during query [for Statement "SHOW GLOBAL STATUS LIKE ?" with ParamValues: 0='Threads_running'] at /usr/bin/pt-online-schema-change line 8806..  Check that the variables specified for --max-load and --critical-load are spelled correctly and exist in SHOW GLOBAL STATUS.  Current values for these options are:

I am not sure what's going wrong here which is making failed to percona to run , as every time looks like percona is losing connection to RDS instance. 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Any help would be highly appreciated.

**Comment by adangel** [comment]
This github project is about the *liquibase* extension to use percona within liquibase, not about percona. So, I can't help you with your percona problem (since you are running percona directly).
Please have a look at https://www.percona.com/doc/percona-toolkit/LATEST/bugs.html for bug reporting for percona.

I think, I've seen the exception (`com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure`) while running the integration tests of this project. It might have to do with either of these things (or something completely different):
* incompatibility between mysql-connector-java and the mysql instance
* some TLS issue (newer mysql versions speak directly TLS) - and that would need proper client configuration

**Comment by chiragag18** [comment]
Thanks @adangel  for your quick response, Also I am using liquibase percona only 1.6.0 jar with percona. This is only happening when my RDS instance has many client connected so it sometime lose the connection.

I thought you will have any idea if I missing any property to set in application level so that I don't get this connection lost issue.

**Comment by adangel** [comment]
I'd suggest to make sure to use the latest version of any db connection library (Perl's DBI mysql driver, mysql-connector-java) and try again.

Looking at the documentation for [--critical-load](https://www.percona.com/doc/percona-toolkit/LATEST/pt-online-schema-change.html#cmdoption-pt-online-schema-change-critical-load):

> Examine SHOW GLOBAL STATUS after every chunk, and abort if the load is too high. The option accepts a comma-separated list of MySQL status variables and thresholds.

And for [--max-load](https://www.percona.com/doc/percona-toolkit/LATEST/pt-online-schema-change.html#cmdoption-pt-online-schema-change-max-load):

> Examine SHOW GLOBAL STATUS after every chunk, and pause if any status variables are higher than their thresholds. The option accepts a comma-separated list of MySQL status variables.

So, percona executes the `SHOW GLOBAL STATUS` command - which sounds very MySQL specific. It seems to be supported by RDS though (https://aws.amazon.com/de/premiumsupport/knowledge-center/rds-instance-high-cpu/).

Maybe this troubleshoot article helps? https://aws.amazon.com/de/premiumsupport/knowledge-center/rds-mysql-server-gone-away/ It suggests to double check any timeouts. Maybe the chunk size doesn't play well with the timeouts? Maybe the packets are too big?

I'm closing this issue, this is unrelated to liquibase percona.
