### ISSUE TITLE
Support addForeignKeyConstraintChange, addUniqueConstraintChange

### ISSUE THREAD

**Issue by adangel** [adangel/liquibase-percona#8]
Example

```
<addForeignKeyConstraint baseTableName="" baseColumnNames="" constraintName="" referencedTableName=""
                                 referencedColumnNames="" />
```

**Comment by adangel** [comment]
In addition to [addForeignKeyConstraint](http://www.liquibase.org/documentation/changes/add_foreign_key_constraint.html),
[addUniqueConstraint](http://www.liquibase.org/documentation/changes/add_unique_constraint.html),
[dropForeignKeyConstraint](http://www.liquibase.org/documentation/changes/drop_foreign_key_constraint.html) and [dropUniqueConstraint](http://www.liquibase.org/documentation/changes/drop_unique_constraint.html) should be supported.

**Comment by dan-n-promethean** [comment]
Agreed. This is super-important for our data model, too.
