### ISSUE TITLE
Support for enabling pt-online-schema-changes on a per-change basis

### ISSUE THREAD

**Issue by deviation** [adangel/liquibase-percona#9]
I was wondering if you'd considered adding support for flagging changesets to use pt-online-schema-change. 

It can be not ideal to run it for every alter. When tables are moved around, there can be milliseconds where lookup tables are not available which can confuse our app. Also I'm told if there are any triggers set up on the table, pt-online-schema-change will not work at all.

It'd be useful to have something along the lines of a 'usePercona' flag on all of the changes implemented by liquibase-percona so we can have better control over how each change is applied.

**Comment by deviation** [comment]
For example:
    <changeSet id="2" author="nvoxland" usePercona="true">
        <addColumn tableName="person">
            <column name="username" type="varchar(8)"/>
        </addColumn>
    </changeSet>

**Comment by adangel** [comment]
This requirement makes sense. Currently, you can only control the execution of all changesets via the java [system property](https://github.com/adangel/liquibase-percona#configuration) `liquibase.percona.skipChanges`. If you execute the changesets in portions (might use contexts), you can selectively execute changesets with pt-osc or without. But it is only a runtime option and easily forgotten.

Attaching the information to a changeset, whether to use pt-osc or not, would be ideal. However, your proposed solution adding a attribute `usePercona` would change the schema and require a liquibase-core change. This is out of scope for an extension.

For a changeset, a context and/or a label can be defined. However, both seem to be used for the same purpose: executing only selected changesets (matching context or label), and not changing the way of execution.

For now, I see 2 ways, which feel like workarounds: Provide another system property, which contains a comma-separated list of changeset Ids, that should not be run via pt-osc. And establish a naming convention and encode this in the changeset id itself, e.g. if the changeset id ends with "-no-percona", that don't run it via pt-osc.

Now, looking at the [schema definition](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/resources/liquibase/parser/core/xml/dbchangelog-3.6.xsd#L200) it seems to be possible to add arbitrary attributes like your suggested `usePercona`. I don't see right now, that these additional attributes would be available later on, but it looks like an interesting enhancment, that's worth to be made upstream. But until then, we would need a different solution, that also works with the current liquibase versions.

What do yout think?

**Comment by deviation** [comment]
Having '-no-percona' in the changeset id seems sort of hacky... and Specifying the changeset ids not to run with percona as a system property isn't ideal for our setup - Ideally that information would live in the changeset itself. 
What about adding a flag to the individual changes, as opposed to the changesets? 
 Ie:

```xml
<changeSet id="2" author="nvoxland">
        <addColumn tableName="person"  usePercona="true">
            <column name="username" type="varchar(8)"/>
        </addColumn>
</changeSet>
```


I was also wondering if it'd be possible to specify a default value for that flag across the board, possibly in a system property.. 'liquibase.percona.defaultOn' or something? We want to require developers to explicitly state the change will be using pt-online-schema-change, and our DBA team can review these manually.

**Comment by adangel** [comment]
Yes, this should work. I also like the idea of having a global switch.
There is one more decision to make: Assuming you have the liquibase-percona plugin active, but you did not use the `usePercona` attribute yet nor you are setting the global switch `liquibase.percona.defaultOn`. How should the plugin behave now? Should it execute pt-osc, like it does now? Or should it execute the statements without pt-osc? Or should it fail and require to update the changelog to set the missing attributes?

In terms of backwards compatibility, it would be the first case. In terms of safety, I would prefer the last case - forcing to update the changelog when updating the plugin. Assuming that one would test this before running the update in production environments, the failure would be obvious...

What do you think?

**Comment by deviation** [comment]
It seems like it might be safer to assume people want to use the plugin for all changes if they're including it in their classpath, but I'm not sure. I don't feel too strongly about how that would work. I was just thinking of backwards compatibility for anyone already using your plugin.

**Comment by adangel** [comment]
Please note: This only works for YAML changelog. It doesn't work with XML changelogs, see https://liquibase.jira.com/browse/CORE-2965

**Comment by deviation** [comment]
Thank you very much!! I'll test this out in the next day or two.

**Comment by deviation** [comment]
Forgot to mention - this works as expected. Thank you for taking the time to make this change!

**Comment by adangel** [comment]
Thank you for testing and the feedback!
